version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: easel_atelier_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: easel_atelier
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: